In [118]:
import pandas as pd
import numpy as np

In [119]:
# Load Raw Banking Data
banking_df = pd.read_csv("banking_raw_data.csv")

## Data Understanding

### Overview of the Dataset
- The dataset inculudes customers banking information, including demographic details, account information, financial records, transaction activity, and customer status. It provides a comprehensive view of customer banking behavior and can be used to analyze financial patterns, customer engagement, and operational performance.
### Types of Information Available
- This dataset includes informtion related to:

    **Customer Demographics**

    **Account details**

    **Loan Information**

    **Transaction Activity**

  **Customer Status**

## Column Understanding 
**Customer ID** : A unique identifier assigned to each customer<br>
**Customer Name** : Name of the customer<br>
**Gender** : Customer's gender.<br>
**Age** : Defines the Age of the customer<br>
**Occupation** : Customers's profession or employment category<br>
**Annual Income** : Customer's annual income in Indian Rupees.<br>
**City** : City where the customer resides.<br>
**State** : State where the customer resides.<br>
**Account Type** : Type of bank account (Saving, Salary, Current). <br>
**Account Open Date** : Date when the bank account was opened.<br>
**Account Balance** : Current balance availabe in the customer's account.<br>
**Avg Monthly Balance** : Average Balance maintained during a month.<br>
**Account Status** : Current status of the account(Active, Dormant, Closed)<br>
**Loan Type** :  Category of load taken by the customer ( Home, Car, Personal, Education, None)<br>
**Loan Amount** : Total Loan Amount Sanctioned to the cutomer.<br>
**EMI** : Monthly installment payable for the load.<br>
**Credit Score** : Numerical Representation of the customer's creditworthiness.<br>
**Monthly Transactions** : Total Number of transactions performed in a month.<br>
**Avg Transaction Amount** : Average value of each transaction.<br>
**UPI Txns** : Number of UPI transactions made in a month.<br>
**Last Transaction Date** : Date of the customer's most recent transaction.<br>
**Churn Status** : Indicates whether the customer has churned(Yes/No)

In [120]:
# Creating a copy of the dataset
df = banking_df.copy()

In [121]:
# shape and size of the dataset
print("Total Rows and Columns in the Dataset =", df.shape)
df.memory_usage(deep=True)

Total Rows and Columns in the Dataset = (50500, 22)

Index                         132
Customer ID                404000
Customer Name             3054387
Gender                    2717518
AGE                        404000
Occupation                2974561
Annual Income (₹)          404000
City                      2804840
State                     2974391
Account Type              2811176
Account Open Date         2979500
Account Balance            404000
Avg Monthly Balance        404000
Account Status            2794405
Loan Type                 2542140
Loan Amount                404000
EMI                        404000
Credit Score               404000
Monthly Transactions       404000
Avg Transaction Amount     404000
UPI Txns                   404000
Last Transaction Date     2979500
Churn Status              2566533
dtype: int64

In [122]:
# Sample data to understand how the data is present or distributed in our dataset
df.sample(10)

,Customer ID,Customer Name,Gender,AGE,Occupation,Annual Income (₹),City,State,Account Type,Account Open Date,Account Balance,Avg Monthly Balance,Account Status,Loan Type,Loan Amount,EMI,Credit Score,Monthly Transactions,Avg Transaction Amount,UPI Txns,Last Transaction Date,Churn Status
25773,125774,Rohan Malhotra,Female,28,Business Owner,830879.71,Bengaluru,Karnataka,Savings,2015-12-16,557374.78,469339.91,Closed,NaN,0.00,0.00,552,78,11999.76,3,2022-12-17,No
14275,114276,Diya Bose,Male,65,Bank Employee,679270.23,Ahmedabad,Gujarat,Savings,2018-01-07,438845.53,431259.63,Active,NaN,0.00,0.00,547,118,18245.62,44,2022-10-14,No
40422,140423,Aarav Sharma,Female,53,Student,208761.88,Kochi,Kerala,Savings,2024-05-16,15354.21,14893.12,Closed,Home,150022.34,706.84,490,99,1327.48,96,2025-06-04,No
42426,142427,Vivaan Nair,Female,54,Retired,597643.60,Surat,Gujarat,Current,2024-01-02,102095.35,81564.79,Closed,Education,1734947.67,12067.67,516,13,9639.61,11,2024-09-07,No
2365,102366,Kabir Joshi,Female,24,Teacher,893257.22,Hyderabad,Telangana,Current,2023-08-13,126284.90,114209.44,Active,NaN,0.00,0.00,521,76,8052.75,15,2025-09-04,No
9287,109288,Vivaan Chauhan,Female,51,Teacher,411165.19,Lucknow,Uttar Pradesh,Current,2022-09-24,180660.50,170768.68,Dormant,Personal,494477.16,2491.08,556,67,1512.35,37,2025-10-21,No
17791,117792,Aarav Pandey,Female,27,Lawyer,NaN,Noida,Uttar Pradesh,Current,2017-01-27,737712.03,573576.94,Active,NaN,0.00,0.00,563,89,5095.17,45,2018-11-27,No
38180,138181,Arjun Verma,Female,54,Sales Executive,651190.98,Chennai,Tamil Nadu,Savings,2017-07-17,323664.36,234287.79,Active,Home,1021762.57,14677.10,516,46,2086.35,36,2021-11-25,No
9563,109564,Rohan Nair,Female,43,Farmer,433277.23,Mumbai,Maharashtra,Savings,2024-08-16,90614.83,66327.11,Active,Car,1071795.87,5771.80,513,38,13415.88,30,2025-09-15,No
11633,111634,Priya Chauhan,Male,24,Teacher,573716.40,Bengaluru,Karnataka,Current,2022-07-10,49103.81,40418.01,Closed,NaN,0.00,0.00,488,86,14188.65,52,2026-03-26,No

In [123]:
df.head()
# to display all the columns without truncating
pd.set_option('display.max_columns', None)
df.head()

,Customer ID,Customer Name,Gender,AGE,Occupation,Annual Income (₹),City,State,Account Type,Account Open Date,Account Balance,Avg Monthly Balance,Account Status,Loan Type,Loan Amount,EMI,Credit Score,Monthly Transactions,Avg Transaction Amount,UPI Txns,Last Transaction Date,Churn Status
0,100001,Arjun Singh,Male,-2,CA,1156259.42,Ahmedabad,Gujarat,Savings,2018-02-17,882229.77,796662.17,Active,NaN,0.00,0.00,508,80,12881.20,54,2018-06-27,No
1,100002,Aarav Saxena,Male,54,Software Engineer,1878614.63,Kochi,Kerala,Salary,2024-05-29,135201.45,118541.89,Active,Home,4218144.52,34790.23,588,24,9294.99,6,2025-05-08,No
2,100003,Kabir Mishra,NaN,54,Government Employee,1284843.84,Indore,Madhya Pradesh,Savings,2017-10-19,1310586.26,1066240.97,Closed,Car,3306560.60,19298.97,512,115,6083.51,46,2024-04-09,No
3,100004,Rohan Patel,Male,55,Student,246305.38,Hyderabad,Telangana,Savings,2023-07-11,29846.16,26584.13,Dormant,Home,351096.60,3593.20,509,39,9796.66,4,2024-06-25,No
4,100005,Aditya Singh,Female,29,CA,3002118.27,Delhi,Delhi,Salary,2020-02-20,1921576.20,1809190.40,Closed,Car,1997824.19,8904.37,568,77,11741.87,40,2022-07-09,No

In [124]:
# Total Columns in the dataset
print(df.columns)

Index(['Customer ID', 'Customer Name', 'Gender', 'AGE', 'Occupation',
       'Annual Income (₹)', 'City', 'State', 'Account Type',
       'Account Open Date', 'Account Balance', 'Avg Monthly Balance',
       'Account Status', 'Loan Type', 'Loan Amount', 'EMI', 'Credit Score',
       'Monthly Transactions', 'Avg Transaction Amount', 'UPI Txns',
       'Last Transaction Date', 'Churn Status'],
      dtype='object')

In [125]:
# Data Types of all the columns in Dataset
print(df.dtypes)

# Last Trasaction Date(object) -> datetime
# Account Open Date(object) -> datetime

Customer ID                 int64
Customer Name              object
Gender                     object
AGE                         int64
Occupation                 object
Annual Income (₹)         float64
City                       object
State                      object
Account Type               object
Account Open Date          object
Account Balance           float64
Avg Monthly Balance       float64
Account Status             object
Loan Type                  object
Loan Amount               float64
EMI                       float64
Credit Score                int64
Monthly Transactions        int64
Avg Transaction Amount    float64
UPI Txns                    int64
Last Transaction Date      object
Churn Status               object
dtype: object

In [126]:
# basic information to understand how the datatypes, and how many null values is present in every column of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50500 entries, 0 to 50499
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             50500 non-null  int64
 1   Customer Name           50500 non-null  object
 2   Gender                  50197 non-null  object
 3   AGE                     50500 non-null  int64
 4   Occupation              50500 non-null  object
 5   Annual Income (₹)       47974 non-null  float64
 6   City                    50500 non-null  object
 7   State                   50500 non-null  object
 8   Account Type            50500 non-null  object
 9   Account Open Date       50500 non-null  object
 10  Account Balance         50500 non-null  float64
 11  Avg Monthly Balance     50500 non-null  float64
 12  Account Status          50500 non-null  object
 13  Loan Type               40268 non-null  object
 14  Loan Amount             50500 non-null  float64
 15  EMI                     50500 non-null  float64
 16  Credit Score            50500 non-null  int64
 17  Monthly Transactions    50500 non-null  int64
 18  Avg Transaction Amount  50500 non-null  float64
 19  UPI Txns                50500 non-null  int64
 20  Last Transaction Date   50500 non-null  object
 21  Churn Status            49993 non-null  object
dtypes: float64(6), int64(5), object(11)
memory usage: 8.5+ MB

In [127]:
# Basis statistics to understand how the data is distributed in the dataset
# Numerical Summary
df.describe()

# Setting the float formatting to show 2 decimal places
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df.describe()

,Customer ID,AGE,Annual Income (₹),Account Balance,Avg Monthly Balance,Loan Amount,EMI,Credit Score,Monthly Transactions,Avg Transaction Amount,UPI Txns
count,50500.00,50500.00,47974.00,50500.00,50500.00,50500.00,50500.00,50500.00,50500.00,50500.00,50500.00
mean,125000.78,39.63,1534203.43,568440.97,489986.34,1981342.14,15343.86,543.36,62.37,12792.09,31.23
std,14437.67,14.14,1520192.80,874170.78,743645.82,2337185.97,20693.63,48.99,33.37,7059.40,26.60
min,100001.00,-2.00,21.09,-6612956.53,701.15,0.00,0.00,250.00,5.00,500.16,0.00
25%,112496.75,29.00,578087.12,92405.46,79664.24,234373.72,1534.97,514.00,34.00,6686.67,9.00
50%,124992.50,38.00,987849.74,273124.93,233266.77,1169426.04,8059.32,539.00,62.00,12785.60,24.00
75%,137505.25,50.00,2033875.07,680957.06,575685.83,2706563.55,19972.36,563.00,91.00,18909.29,47.00
max,150000.00,130.00,8997265.97,11444743.08,9978893.81,9000000.00,149703.64,950.00,120.00,24999.68,120.00

In [128]:
# Categorical Summary of the dataset
df.describe(include = 'O')

,Customer Name,Gender,Occupation,City,State,Account Type,Account Open Date,Account Status,Loan Type,Last Transaction Date,Churn Status
count,50500,50197,50500,50500,50500,50500,50500,50500,40268,50500,49993
unique,360,7,12,40,13,3,4675,3,4,3865,2
top,Sneha Sharma,Male,CA,Noida,Uttar Pradesh,Current,2020-03-21,Dormant,Education,2026-07-04,No
freq,175,24376,4329,2593,10266,16946,29,16905,10136,98,49327

In [185]:
# Missing Value Percentage in the Dataset
missing = df.isna().sum().to_frame("Missing_values")
missing['Missing_Value_Percentage'] = (missing["Missing_values"] / len(df))*100
missing['Missing_Value_Percentage'].to_frame()

                        Missing_Value_Percentage
Customer ID                                 0.00
Customer Name                               0.00
Gender                                      0.60
AGE                                         0.00
Occupation                                  0.00
Annual Income (₹)                           5.00
City                                        0.00
State                                       0.00
Account Type                                0.00
Account Open Date                           0.00
Account Balance                             0.00
Avg Monthly Balance                         0.00
Account Status                              0.00
Loan Type                                  20.26
Loan Amount                                 0.00
EMI                                         0.00
Credit Score                                0.00
Monthly Transactions                        0.00
Avg Transaction Amount                      0.00
UPI Txns                                    0.00
Last Transaction Date                       0.00
Churn Status                                1.00

In [196]:
# Unique values present in the dataset for further analysis (if Analysis Required)
def check_unique_values(df):
    unique_values = {
        "Gender": df['Gender'].unique(),
        "Account Type": df['Account Type'].unique(),
        "Account Status": df['Account Status'].unique(),
        "Loan Type" : df['Loan Type'].unique(),
        "Churn Status": df['Churn Status'].unique()
    
    }
    return unique_values

unique_values = check_unique_values(df)



for key, value in unique_values.items():
    print(f"{key} : {value}")

Gender : ['Male' nan 'Female' 'F' 'M' 'female' 'male' 'Femle']
Account Type : ['Savings' 'Salary' 'Current']
Account Status : ['Active' 'Closed' 'Dormant']
Loan Type : [nan 'Home' 'Car' 'Personal' 'Education']
Churn Status : ['No' 'Yes' nan]

In [240]:
# Range Validation
columns = [
    "AGE",
    'Annual Income (₹)',
    'Account Balance',
    'Avg Monthly Balance',
    'Loan Amount',
    'EMI',
    'Credit Score',
    'Monthly Transactions',
    'Avg Transaction Amount',
    'UPI Txns'
]

range_validation = pd.DataFrame({
    "Minimum Value" : df[columns].min(),
    "Maximum Value" : df[columns].max()
})
range_validation


# Expected Values of the Bussiness  Problems
expected_range = {
    'AGE' : '18-100',
    'Annual Income (₹)' : '>=10000 ',
    'Account Balance' : '> 0',
    'Avg Monthly Balance' : '>= 10000',
    'Loan Amount' : '>= 5000',
    'EMI' : '>0',
    'Credit Score': '200-900',
    'Monthly Transactions' : '>500',
    'Avg Transaction Amount' : '>0',
    'UPI Txns' : '>0'
}

range_validation['expected_range'] = range_validation.index.map(expected_range)
range_validation

                        Minimum Value  Maximum Value expected_range
AGE                             -2.00         130.00         18-100
Annual Income (₹)               21.09     8997265.97       >=10000
Account Balance           -6612956.53    11444743.08            > 0
Avg Monthly Balance            701.15     9978893.81       >= 10000
Loan Amount                      0.00     9000000.00        >= 5000
EMI                              0.00      149703.64             >0
Credit Score                   250.00         950.00        200-900
Monthly Transactions             5.00         120.00           >500
Avg Transaction Amount         500.16       24999.68             >0
UPI Txns                         0.00         120.00             >0

In [200]:
# Identify Quality Issue 
def data_quality_check(df):
    quality_report = {
        "total_records" : len(df),
        "duplicate_records" : df.duplicated().sum(),
        "missing_values" : df.isna().sum().to_dict(),
        "incorrect_age_value" : df[(df['AGE'] < 0) | (df['AGE'] > 100)].shape[0],
        "gender_description" : df['Gender'].value_counts().to_dict(),
        "incorrect_account_balance" : df[(df['Account Balance'] < 0)].shape[0],
    
    }
    return quality_report
quality_report = data_quality_check(df)


for key,value in quality_report.items():
    print(f"{key} : {value}")

total_records : 50500
duplicate_records : 1
missing_values : {'Customer ID': 0, 'Customer Name': 0, 'Gender': 303, 'AGE': 0, 'Occupation': 0, 'Annual Income (₹)': 2526, 'City': 0, 'State': 0, 'Account Type': 0, 'Account Open Date': 0, 'Account Balance': 0, 'Avg Monthly Balance': 0, 'Account Status': 0, 'Loan Type': 10232, 'Loan Amount': 0, 'EMI': 0, 'Credit Score': 0, 'Monthly Transactions': 0, 'Avg Transaction Amount': 0, 'UPI Txns': 0, 'Last Transaction Date': 0, 'Churn Status': 507}
incorrect_age_value : 507
gender_description : {'Male': 24376, 'Female': 24233, 'M': 355, 'female': 321, 'F': 316, 'male': 310, 'Femle': 286}
incorrect_account_balance : 303

## Initial Observations 
**Missing Values**<br>
- Missing values are present in multiple columns.
- These missing values need further investigation to determine whether they can be imputed or if the affected records should be removed.<br><br>
**Duplicate Record**<br>
- The dataset contains Multiple duplicate rows.<br><br>
**DataType Issue** <br>
- Date columns such as Account Open Date and Last Transaction Date are stored as object data types.
- This should be converted into datatime formate for proper analysis<br><br>
**Inconsistent Columns**<br>
- categorical columns contain inconsistent formatting, such as different letter cases, abbreviations, blank values, and extra spaces.<br><br>
**Invalid Numerical Values**<br>
- **Range validation** identified values outside the expected business limits in some numerical columns, including:
- Invalid ages
- Invalid credit scores
- Negative account balances
- These records should be investigated and handled appropriately.<br><br>